spring:
  application:
    name: SimpleBoard

  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80